### ISSUE TITLE
업장 CRUD 기능 구현

### ISSUE THREAD

**Issue by KAPUIST** [KAPUIST/Node_Food_Delivery_Service#5]
### 기능 설명
"사장님"은 자신의 업장 정보를 등록, 수정, 삭제할 수 있어야 합니다. 모든 사용자는 업장 정보를 조회할 수 있어야 합니다.

### 세부 내용
- 업장 데이터베이스 테이블 생성 (`Restaurant`)
- 업장 정보 등록 API 구현 (`POST /api/restaurant`)
- 업장 정보 수정 API 구현 (`PUT /api/restaurant/:id`)
- 업장 정보 삭제 API 구현 (`DELETE /api/restaurant/:id`)
- 업장 정보 조회 API 구현 (`GET /api/restaurant`)

**Comment by clearghost3** [comment]
Complete make CRUD of restaurant.
